### ISSUE TITLE
Inconsistent capitalization in code and folders.

### ISSUE THREAD

**Issue by dclancy89** [mossyfred/Broadway#1]
In your HTML file you have 
` <link href="./resources/css/style.css" type="text/css" rel="stylesheet">`

which has the path names all lower case, but in the repository you have Resources capitalized, and CSS in all caps. The HTML file won't be able to link to the css file or the images because it's looking for folders in all lower case.

**Comment by mossyfred** [comment]
Thanks Daniel, I had some problems having some of the background images load, probably for that reason. Time to ditch the caps.

**Comment by mossyfred** [comment]
Figuring out how to delete directories from gitHub, add a "new" one with the same name that was lower case all while in git bash was an adventure in itself but thanks for pointing me int he right direction, looks like my issues were resolved.. definitely could use more practice with git.
